#!/usr/bin/env bash
#
# Netdata Post-Install Configuration for Proxmox VE
# Configures Netdata to detect and monitor LXC containers on cgroups v2 systems
#
# LICENSE & DISCLAIMER:
# This script is provided "AS IS", without warranty of any kind, express or
# implied, including but not limited to the warranties of merchantability,
# fitness for a particular purpose and noninfringement. In no event shall the
# authors or copyright holders be liable for any claim, damages or other
# liability, whether in an action of contract, tort or otherwise, arising from,
# out of or in connection with the software or the use or other dealings in the
# software.
#
# Use this script at your own risk. The authors are not responsible for any
# data loss, system instability, or service downtime caused by running it.
#
# Features:
# - Detects cgroups v2 unified hierarchy on Proxmox VE
# - Configures Netdata cgroups plugin for LXC container monitoring
# - Adds netdata user to www-data group for /etc/pve access
# - Resolves container VMIDs to friendly names via /etc/pve/lxc/*.conf
# - Creates drop-in configuration to survive Netdata upgrades

set -Eeuo pipefail

SCRIPT_VERSION="v1.0.0"

# --- LOGGING ---
LOG_STDOUT="${LOG_STDOUT:-yes}"

log() {
  local level="${1:-INFO}"
  shift
  local timestamp
  printf -v timestamp '%(%Y-%m-%d %H:%M:%S)T' -1
  local message="${timestamp} [${level}] $*"

  if [[ "${LOG_STDOUT}" == "yes" ]]; then
    printf '%s\n' "$message" >&2
  fi

  if command -v logger &>/dev/null; then
    logger -t "netdata-postinstall" -p "user.${level,,}" -- "$*" 2>/dev/null || true
  fi
}

# --- PREFLIGHT CHECKS ---
if [[ $EUID -ne 0 ]]; then
  log ERROR "This script must be run as root"
  exit 1
fi

if ! command -v pct &>/dev/null; then
  log ERROR "Proxmox VE commands (pct) not found. Are you running this on a PVE host?"
  exit 1
fi

if ! command -v netdata &>/dev/null && ! systemctl is-active --quiet netdata 2>/dev/null; then
  log ERROR "Netdata is not installed or not running. Install it first:"
  log ERROR "  bash -c \"\$(curl -fsSL https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/tools/addon/netdata.sh)\""
  exit 1
fi

# --- DETECT CGROUP VERSION ---
detect_cgroup_version() {
  local fstype
  fstype=$(stat -fc %T /sys/fs/cgroup 2>/dev/null || echo "unknown")

  if [[ "$fstype" == "cgroup2fs" ]]; then
    echo "v2"
  elif [[ "$fstype" == "tmpfs" ]]; then
    echo "v1"
  else
    echo "unknown"
  fi
}

CGROUP_VERSION=$(detect_cgroup_version)
log INFO "Detected cgroups version: $CGROUP_VERSION"

if [[ "$CGROUP_VERSION" == "v1" ]]; then
  log INFO "cgroups v1 detected. Netdata should discover LXC containers automatically."
  log INFO "If containers are not visible, run this script again after upgrading to cgroups v2."
  exit 0
fi

if [[ "$CGROUP_VERSION" == "unknown" ]]; then
  log ERROR "Could not determine cgroup version. Check /sys/fs/cgroup mount."
  exit 1
fi

# --- ADD NETDATA USER TO WWW-DATA GROUP ---
add_netdata_to_wwwdata() {
  if id -nG netdata 2>/dev/null | grep -qw www-data; then
    log INFO "netdata user is already in www-data group"
    return 0
  fi

  if ! getent group www-data &>/dev/null; then
    log WARN "www-data group does not exist. Creating it..."
    groupadd www-data
  fi

  usermod -a -G www-data netdata
  log INFO "Added netdata user to www-data group"
}

add_netdata_to_wwwdata

# --- VERIFY /etc/pve ACCESS ---
verify_pve_access() {
  if [[ ! -d /etc/pve/lxc ]]; then
    log WARN "/etc/pve/lxc directory not found. Container name resolution may not work."
    return 1
  fi

  local container_count
  container_count=$(find /etc/pve/lxc -name "*.conf" 2>/dev/null | wc -l)
  log INFO "Found $container_count LXC container configurations in /etc/pve/lxc/"
  return 0
}

verify_pve_access

# --- CREATE DROP-IN CONFIGURATION ---
NETDATA_CONF_DIR="/etc/netdata/netdata.conf.d"
NETDATA_CGROUPS_CONF="${NETDATA_CONF_DIR}/proxmox-cgroups-v2.conf"

mkdir -p "$NETDATA_CONF_DIR"

if [[ -f "$NETDATA_CGROUPS_CONF" ]]; then
  log INFO "Backing up existing configuration to ${NETDATA_CGROUPS_CONF}.bak"
  cp "$NETDATA_CGROUPS_CONF" "${NETDATA_CGROUPS_CONF}.bak"
fi

cat > "$NETDATA_CGROUPS_CONF" << 'EOF'
# Netdata cgroups v2 configuration for Proxmox VE LXC containers
# Generated by netdata-postinstall.sh
# This file survives Netdata upgrades via drop-in directory

[plugin:cgroups]
  # Search all cgroup subpaths (no exclusions for LXC)
  search for cgroups in subpaths matching = !*/init.scope !*-qemu !*.libvirt-qemu !/init.scope !/system !/systemd !/user *

  # Enable LXC containers on cgroups v2 (path: /lxc/<vmid>/)
  # Removed exclusions: !/lxc, !/lxc/*/*, !/lxc.monitor*, !/lxc.pivot, !/lxc.payload
  # Added: /lxc/* to enable all container cgroups
  enable by default cgroups matching = !*/init.scope !/system.slice/run-*.scope *user.slice/docker-* !*user.slice* *.scope !/machine.slice/*/.control !/machine.slice/*/payload* !/machine.slice/*/supervisor /machine.slice/*.service */kubepods/pod*/* */kubepods/*/pod*/* */*-kubepods-pod*/* */*-kubepods-*-pod*/* !*kubepods* !*kubelet* !*/vcpu* !*/emulator !*.mount !*.partition !*.service !*.service/udev !*.socket !*.slice !*.swap !*.user !/ !/docker !*/libvirt !/lxc.monitor* !/lxc.pivot !/lxc.payload !*lxcfs.service/.control !/machine !/qemu !/system !/systemd !/user /lxc/* *

  # Run cgroup-name helper to resolve VMID to container names
  run script to rename cgroups matching = !/ !*.mount !*.socket !*.partition /machine.slice/*.service !*.service !*.slice !*.swap !*.user !init.scope !*.scope/vcpu* !*.scope/emulator *.scope *docker* *lxc* *qemu* */kubepods/pod*/* */kubepods/*/pod*/* */*-kubepods-pod*/* */*-kubepods-*-pod*/* !*kubepods* !*kubelet* *.libvirt-qemu *

  # Use the Netdata cgroup-name helper for name resolution
  script to get cgroup names = /usr/libexec/netdata/plugins.d/cgroup-name.sh
  cgroup-name timeout = 120
EOF

log INFO "Created drop-in configuration: $NETDATA_CGROUPS_CONF"

# --- VERIFY CGROUP-NAME HELPER ---
CGROUP_NAME_HELPER="/usr/libexec/netdata/plugins.d/cgroup-name.sh"
CGROUP_NAME_BINARY="/usr/libexec/netdata/plugins.d/cgroup-name"

if [[ ! -x "$CGROUP_NAME_HELPER" ]] && [[ ! -x "$CGROUP_NAME_BINARY" ]]; then
  log WARN "cgroup-name helper not found at $CGROUP_NAME_HELPER or $CGROUP_NAME_BINARY"
  log WARN "Container names may show as numeric VMIDs instead of friendly names"
  log WARN "Check Netdata installation or reinstall"
else
  log INFO "cgroup-name helper found and executable"
fi

# --- CHECK CGROUP CONTROLLER DELEGATION ---
SUBTREE_CONTROL="/sys/fs/cgroup/lxc/cgroup.subtree_control"
if [[ -f "$SUBTREE_CONTROL" ]]; then
  log INFO "Current subtree controllers: $(cat "$SUBTREE_CONTROL")"
else
  log WARN "Could not read $SUBTREE_CONTROL. Controllers may not be delegated to containers."
fi

# --- RESTART NETDATA ---
log INFO "Restarting Netdata..."
if systemctl restart netdata; then
  log INFO "Netdata restarted successfully"
else
  log ERROR "Failed to restart Netdata. Check: journalctl -u netdata --since '2 min ago'"
  exit 1
fi

# --- WAIT AND VERIFY ---
log INFO "Waiting 30 seconds for Netdata to initialize..."
sleep 30

# Check if containers are being discovered
JOURNAL_OUTPUT=$(journalctl -u netdata --since "1 min ago" 2>/dev/null | grep -i "cgroup\|lxc" | tail -10 || true)
if [[ -n "$JOURNAL_OUTPUT" ]]; then
  log INFO "Netdata cgroup discovery output:"
  echo "$JOURNAL_OUTPUT" | while IFS= read -r line; do
    log INFO "  $line"
  done
fi

# --- SUMMARY ---
log INFO "=== Post-Install Complete ==="
log INFO "Cgroup version: $CGROUP_VERSION"
log INFO "Drop-in config: $NETDATA_CGROUPS_CONF"
log INFO "Access Netdata at: http://$(hostname -I | awk '{print $1}'):19999"
log INFO ""
log INFO "If containers are not visible in the dashboard:"
log INFO "  1. Check logs: journalctl -u netdata --since '5 min ago' | grep -i lxc"
log INFO "  2. Verify config: cat $NETDATA_CGROUPS_CONF"
log INFO "  3. Check permissions: sudo -u netdata ls /etc/pve/lxc/"
log INFO "  4. Verify controllers: cat $SUBTREE_CONTROL"
